### PR TITLE
chore: set up auto for versioning/release management 

### PR DESCRIPTION
**Pull request by hydrosquall**
## Motivation

- See the Vega project board: https://github.com/orgs/vega/projects/8#card-65695504

## Changes

- Based on lessons from https://github.com/vega/vega-tooltip/pull/566

## Pre-merge checklist for a repo admin

- [x] Create a branch called `next` from the current head of `master` [link](https://github.com/vega/vega-lite-dev-config/tree/next)
   - [x] make that the base branch of this PR instead of `master`
- [x] Create a branch called `stable` from the tag  `0.18` [link](https://github.com/vega/vega-lite-dev-config/tree/stable)
- [x] Make a tagged release of `0.18.0` on github (this will avoid the tall changelog issue that we encountered with `vega-tooltip`: https://github.com/vega/vega-lite-dev-config/releases/tag/v0.18.0
- [x] Create tags called `skip-release` and `released` in this repo (the first is used to tell auto not to release anything if this PR is released, the second is used to tag PRs that have been released).

### CODE REVIEW

**Comment by domoritz** [comment]
@hydrosquall I gave you maintenance permissions on this repo. Please go ahead and set up the release process.

**Comment by hydrosquall** [comment]
@domoritz thanks for adding those permissions.

I've set up everything in the checklist except for changing the default branch of the repository, since I don't have access to that with my permission level. After we change the base branch, I think this is ready to merge.

**Comment by domoritz** [comment]
I just moved into a new house and don't have internet yet. I'll set up the branches when I get to a place with WiFi.

**Comment by domoritz** [comment]
Done. `next` is now the default.

**Pull request merged**
